### ISSUE TITLE
i2c_bcd_datetime.py set property does not except time.struct_time as value

### ISSUE THREAD

**Issue by mrmcwethy** [adafruit/Adafruit_CircuitPython_Register#2]
I was using the adafruit_ds3231 to set the correct time on that device.  The datetime property fails if provided a time.struct_time object.  The i2c_bcd_datetime set property reference 'second', 'minute', etc.  Should be 'tm_sec','  tm_min' etc.  This would make this class consistent with i2c_bcd_alarm.py set property.

**Comment by tannewt** [comment]
Yup! Good idea! Want to try doing it yourself?

**Comment by mrmcwethy** [comment]
Sure.  I would love to.
Mike


Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: Scott Shawcroft <notifications@github.com> Date: 8/2/17  10:12 AM  (GMT-08:00) To: adafruit/Adafruit_CircuitPython_Register <Adafruit_CircuitPython_Register@noreply.github.com> Cc: Michael McWethy <mrmcwethy@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [adafruit/Adafruit_CircuitPython_Register] i2c_bcd_datetime.py
  set property does not except time.struct_time as value (#2) 
Yup! Good idea! Want to try doing it yourself?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adafruit/Adafruit_CircuitPython_Register","title":"adafruit/Adafruit_CircuitPython_Register","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/adafruit/Adafruit_CircuitPython_Register"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tannewt in #2: Yup! Good idea! Want to try doing it yourself?"}],"action":{"name":"View Issue","url":"https://github.com/adafruit/Adafruit_CircuitPython_Register/issues/2#issuecomment-319737665"}}}

**Comment by tannewt** [comment]
Awesome! Let me know if you have any questions.

**Comment by mrmcwethy** [comment]
I made the change (i think).  I tested the change on a Circuit Playground Express board by copying the .py file into the adafruit_register folder and deleting the .mpy file.  Made the change directly in GitHub and made a pull request.  Let me know the "real" process.

**Comment by tannewt** [comment]
Pull request is the preferred method! Check out this [learn guide](https://learn.adafruit.com/an-introduction-to-collaborating-with-version-control/os-x?view=all) if you want to learn more about `git`. Thanks!

I've merged your pull in 082f62b7678ad925a71f4a43bb2665a8a1f063c0.
