### ISSUE TITLE
On the Trinket M0, I2c doesn't work due to Mar 6 'reversed' addition

### ISSUE THREAD

**Issue by jepye** [adafruit/Adafruit_CircuitPython_Register#24]
Trying to run code on the Trinket M0 with only the adafruit_bus_device, adafruit_fancyled, adafruit_register, led_animation, adafruit_amg88.mpy, adafruit_dotstar.mpy, and neopixel.mpy libraries installed, I keep getting an error when it tries to use I2c:

Traceback (most recent call last):
  File "code.py", line 11, in <module>
  File "adafruit_amg88xx.py", line 128, in __init__
  File "adafruit_register/i2c_bits.py", line 90, in __set__
  File "adafruit_register/i2c_bits.py", line 87, in __set__
NameError: name 'reversed' is not defined

It appears the change on Mar 20 that added 'reversed' broke it.  When I load the previous version, it works just fine.

**Comment by ladyada** [comment]
oi @dhalbert do we not have enough space for `reversed`? i can hand-implement but its a handy list mangler

**Comment by dhalbert** [comment]
I might be able to add it; we deleted some other stuff that could make room. I'll try a trial build with the largest translations.

**Comment by dhalbert** [comment]
It fits!
