### ISSUE TITLE
Documentation: "API" and "Indices and Tables" incorrectly populated

### ISSUE THREAD

**Issue by hukuzatuna** [adafruit/Adafruit_CircuitPython_Register#4]
In the project documentation, the "API" and "Indices and Tables" sections are populated with code snippets instead of documentation. For example, the API section reads:

.. toctree::
    :maxdepth: 3

    adafruit_register/index

This problem occurs in many places. If need be I can generate a list.

**Comment by tannewt** [comment]
This is a GitHub vs ReadTheDocs weirdness. Its fine on ReadTheDocs: https://circuitpython.readthedocs.io/projects/register/en/latest/

We should add a ReadTheDocs link to the page so its clear that people should click over.

**Comment by dhalbert** [comment]
The `toctree` stuff no longer shows up in the rendered README. I didn't add a link to RTD, but this problem is true for many libraries (no link to RTD), so I'm closing this in favor of at some point maybe adding RTD links to all library README's.
