### ISSUE TITLE
Feature Request: Allow to set a delay when reading

### ISSUE THREAD

**Issue by a-mueller** [adafruit/Adafruit_CircuitPython_Register#47]
I am trying to use this to create a library for the HDC1080 temperature / humidity sensor. I understand from the data sheet that one has to wait for 6.5ms after writing to the register address before reading from it. The `UnaryStruct` however does this: `i2c.write_then_readinto` which reads immediately. Would be great if you could specify a read timeout on initialization.

**Comment by ladyada** [comment]
write_then_readinto is really special, and there's no way to guarantee a delay (because of how linux does repeated-start transactions) so your best bet is really two hvae two transactions for reading and writing!

**Comment by a-mueller** [comment]
Thanks, so any chance that something like this would get added? I assume something similar to this (in `UnaryStruct`):

```python
def __get__(self, obj, objtype=None):
    buf = bytearray(1 + struct.calcsize(self.format))
    buf[0] = self.address
    with obj.i2c_device as i2c:
        i2c.write(buf, end=1)
        
    time.sleep(self.read_delay)
    
    with obj.i2c_device as i2c:
        i2c.readinto(self._BUFFER, start=1)

    return struct.unpack_from(self.format, buf, 1)[0]

```

**Comment by ladyada** [comment]
we woudl not split 'write_readinto' into two funcitons, it would break a lot of stuff. write_readinto is special!

**Comment by tannewt** [comment]
@a-mueller I'd recommend copying the implementation of UnaryStruct into your driver, renaming it and changing it to meet your needs. There is no reason for us to change it in this shared library to support a single driver.

**Comment by a-mueller** [comment]
Thanks, I figured this will be the case.
